# Main config file for PDBH
# Find out more here: https://www.github.com/Englishexe/pdbh/wiki
Output:
  # Terminal outputs

  pdbhPrefix: "[PDBH] "
  # The prefix before every PDBH message, can be blank.
  # Default: "[PDBH] "
  # Example: "[PDBH] Wrote data to database"


  pdbhOutputsInfo: True
  # Should PDBH output generic information to the terminal
  # If Log.pdbhLogs is True they will also appear there
  # Default: True
  # Example: "[PDBH] Wrote data to database"


  pdbhOutputsWarnings: True
  # Should PDBH output warnings to the terminal
  # If Log.pdbhLogs is True they will also appear there
  # Default: True
  # Example: "[PDBH] Database already exists"


  pdbhOutputsErrors: True
  # Should PDBH output errors to the terminal, I highly suggest this is True
  # If Log.pdbhLogs is True they will also appear there
  # Default: True
  # Example: "[PDBH] Database is corrupted"


Log:
  pdbhLogs: True
  # Should PDBH log all messages to a file
  # Info, Error & Warning settings are ignored, all messages will log if this is True
  # Default: True


  pdbhLogFile: "PDBH.log"
  # Where should PDBH log to, this setting depends on Log.pdbhLogs
  # I would suggest leaving this as default as it is unique enough
  # Default: "PDBH.log"


Database:
  pdbhGhost: False
  # If True PDBH will not write to databases, useful for testing out functions.
  # Instead of writing to databases it will be outputted to Terminal & Log as an INFO
  # Default: False

  pdbhDatabaseDirectoryName: "PDBHDatabases"
  # Where should all databases be held
  # If you have pre-existing databases do NOT change this, they will disappear
  # Default: "PDBHDatabases"

  pdbhExampleData: "[[['A'],['B'],['C'],['D']],[['Alpha1'],['Beta1'],['Charlie1'],['Delta1'],['Alpha2'],['Beta2'],['Charlie2'],['Delta2'],['Alpha3'],['Beta3'],['Charlie3'],['Delta3']]]"
  # A set of data that PDBH can use as an example
  # Changing this could break new databases, to create empty databases use pdbh.createEmptyDatabase(X,X)
  # Default: SEE WIKI

  pdbhFileSuffix: ".pdbh"
  # What file 'extension' should pdbh store in, makes no difference really
  # If you have pre-existing databases do NOT change this, they will disappear
  # Default: ".pdbh"

Networking:
  pdbhNetworking: True
  # Should PDBH make network requests, like to find the latest version number or...
  # install tools when needed
  # PDBH doesn't sell your data to Chinese governments so I would leave this True
  # Default: True

  pdbhNetworkingURL: "68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f456e676c6973686578652f706462685265736f75726365732f6d61696e2f"
  # Do not change this, a prefix for PDBH to quickly find resources
  # Seriously you WILL break stuff if this is changed
  # Default: "https://raw.githubusercontent.com/Englishexe/pdbhResources/main/"

Config:
  configVersion: 0.0.1
  # DO NOT CHANGE
  # For updating script
